栗山担当分 "「小さなアプリバイナリを構築する」で使用したサンプルコードをビルドする" を追加
yumemi-inc/daigirin-tbf16 pull request #13
Opened 2024-04-22 01:05 UTC by kotetuco

## 概要
`「小さなアプリバイナリを構築する」で使用したサンプルコードをビルドする` を執筆しました。

### 確認項目

- [x] `make run` で PDF が出力される
- [x] 可能な範囲で lint エラーに対応した

### 備考
- ブログ記事としての公開も検討しますが、現時点でまだ具体的なことは決まっていません。

2024-04-22 03:05 UTC, mitsuharu requested changes
ありがとうございます！気になったところをコメントしました！

2024-04-22 03:05 UTC, mitsuharu commented on book/manuscripts/kotetu.md
> +</div>
[MUST]
この `</div>` は不要だと思うので、削除をお願いします！

2024-04-22 03:05 UTC, mitsuharu commented on book/manuscripts/kotetu.md
> +なお、本稿では macOS を用いてビルドを行っています。 Linux や Windows 環境でビルドを行う場合は、ダウンロードする Snapshot や手順が異なります。
[IMO]
macOSだけなく、macOS のバージョン（Ventura 13.6.3など）、コアの種類（M1 Pro など）もあると、読者が再現するときに環境確認（依存）に参考になると思います。

2024-04-22 03:05 UTC, mitsuharu commented on book/manuscripts/kotetu.md
> +"try! Swift 2024" [^1]で発表された "小さなアプリバイナリを構築する" [^2] は、筆者にとって興味深い内容でした。
[nits]
`"try! Swift 2024"`だと引用符（クォーテーションマーク）の閉じが気になりました。
`“try! Swift 2024”`とすると適用範囲がわかりやすいです。ただし、使用箇所が多いので、このままでもよいです。

2024-04-22 07:04 UTC, ykws reviewed
手元でも試してみたくなる内容でした
Request changes ではないですが、気になった箇所をコメントさせて頂きました

2024-04-22 07:04 UTC, ykws commented on book/manuscripts/kotetu.md
> +1. Trunk Development の Snapshot をインストールする
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
前提知識なしで読んでいたので、これが何を指しているのか引っ掛かりました。
Swift だとは思ったのですが、 macOS 環境なので Xcode をインストールする理解であってそうでしょうか？
macOS を前提と明記しているので、 Xcode と明記してあると驚きが少ないかもです

https://www.swift.org/download/

2024-04-22 07:04 UTC, ykws commented on book/manuscripts/kotetu.md
> +1. Trunk Development の Snapshot をインストールする
とコメントした後に具体的に説明を読んで、
**Xcode 向けのコマンドラインツール一式** が正確でしょうか

2024-04-22 07:04 UTC, ykws commented on book/manuscripts/kotetu.md
> +case .linux, .openbsd:
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

default のエラーハンドリングがなくなってしまうので、 `fatalError` の方は元に戻して、次のように `case` を修正する方が安全に感じました

```suggestion
case .linux, .openbsd, noneOS:
```

2024-04-22 07:04 UTC, ykws commented on book/manuscripts/kotetu.md
> +という箇所があるので、次のように書き換えます。
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

パスが katei さんのローカルパスになっているので、実行環境に合わせてパスを変更する、ということを明記してもらっても良さそうです

2024-04-22 17:43 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +"try! Swift 2024" [^1]で発表された "小さなアプリバイナリを構築する" [^2] は、筆者にとって興味深い内容でした。
ありがとうございます！改めて検討しましたが、鉤括弧の方がPDF出力した際の印象が良かったので、鉤括弧に置き換えようと思います 🙏

2024-04-22 17:56 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +1. Trunk Development の Snapshot をインストールする
> Xcode 向けのコマンドラインツール一式 が正確でしょうか

https://www.swift.org/download/ でダウンロードできるのは、「Swift のコマンドラインツール一式」という表現が正しいと思います。Xcode でのみ使われるわけではなく、この記事のようにXcode を介さずコマンドを呼び出す用途もあるはずです。

何を指しているのか分かりにくいというのは、おっしゃる通りだと感じたので、何か補足で説明を入れてみようと思います！

コメントありがとうございます 🙇

2024-04-22 19:40 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +case .linux, .openbsd:
今回の修正は https://github.com/apple/swift-package-manager/pull/7417 で提案されている内容をそのまま持ってきています。

PR の中では該当しないcaseはすべて拡張子 ".so" (共有ライブラリ)にまとめる方向で進めようとしていますが、今回の記事に関しては、`.noneOS` の場合に限定した話になるので、より修正範囲を局所的にする意味でもご提案いただいた方法の方が良さそうに思いました。 

PRで提案された方法とは少し異なる方法になることから、若干修正に関する経緯について追記を入れつつ、ご提案いただいた方法での修正にしたいと思います。

2024-04-22 20:10 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +なお、本稿では macOS を用いてビルドを行っています。 Linux や Windows 環境でビルドを行う場合は、ダウンロードする Snapshot や手順が異なります。
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/be0e164026c2afe6c9e7656e2cf5ac206b4fe121 で追記しました！

2024-04-22 20:10 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +"try! Swift 2024" [^1]で発表された "小さなアプリバイナリを構築する" [^2] は、筆者にとって興味深い内容でした。
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/a695cd8a2dbe07b8d0d569f5b24dfac4bd9a4aa8 で対応しました！

2024-04-22 20:11 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +</div>
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/03dcc532f567735a9a063e7a4549309252ee33e3 で修正しました！

2024-04-22 20:11 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +1. Trunk Development の Snapshot をインストールする
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/d77619c9677771fd71b20804099b8a721ab0a788 で対応しました！

2024-04-22 20:12 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +case .linux, .openbsd:
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/316e5d317f9490d35ced716e81fdc64a0982f2d1 で対応しました！

2024-04-22 20:12 UTC, kotetuco commented on book/manuscripts/kotetu.md
> +という箇所があるので、次のように書き換えます。
こちら https://github.com/yumemi-inc/daigirin-tbf16/pull/13/commits/cc18b4ec4cd98bb79219e4140aa47f0e423a56a4 で対応しました！

2024-04-22 23:53 UTC, mitsuharu approved these changes
╭( ･ㅂ･)و ̑̑ 

@ykws 変更点の確認お願いします🙏

2024-04-23 01:21 UTC, ykws approved these changes
LGTM 👍

2024-04-23 01:31 UTC, mitsuharu commented
@kotetuco 入稿のための作業をすすめるため、こちらでマージします！

2024-04-23 01:31 UTC, merged