【井関】TextFieldを数字のみだけでなく、小数点も使えるようにする方法の執筆をしました
yumemi-inc/daigirin-tbf16 pull request #4
Opened 2024-04-10 07:55 UTC by iseruuuuu

# 概要
- TextFieldを数字のみだけでなく、小数点も使えるようにする方法の執筆をしました

# PDF
[ebook.pdf](https://github.com/yumemi-inc/daigirin-tbf16/files/14929315/ebook.pdf)

2024-04-10 07:55 UTC, iseruuuuu commented
@yumemi-inc/daigirin-tbf16 
お手隙の際にレビューお願いします

2024-04-10 08:46 UTC, usami-k requested changes
早めに原稿を仕上げておられて素晴らしいです！
mustを含む何点かのレビューコメントをしました。

2024-04-10 08:46 UTC, usami-k commented on book/manuscripts/iseki.md
> +では実装した内容をご紹介します。
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
この部分でも、視覚的にわかりやすくするため、UIのスクリーンショットなどを貼ると良いと思います。

2024-04-10 08:46 UTC, usami-k commented on book/manuscripts/iseki.md
> +今回は、TextField についての記事はいくつかありましたが、「数字のみ」かつ「小数点は 2 文字目以降の入力ができる」という実装の記事が見つからなかったので、実装してみました。
![must-badge](https://img.shields.io/badge/review-must-red.svg)
Flutterの話かと思いますが、その旨が書かれていないようです。そういった前提を書き足していただければと思います！

2024-04-10 08:46 UTC, usami-k commented on book/manuscripts/iseki.md
> +<hr class="page-break"/>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ここは、「数字のみの制限にする」という話が終わり、新しい話が始まる箇所かと思います。そのため、新しいセクションにするのが良いと思います。

また、改ページを挿入する必要はないと思いました。

2024-04-10 08:46 UTC, usami-k commented on book/manuscripts/iseki.md
> +数字のみの制限をするのはとても簡単に作ることができます。たった 2 行で実装することができます。
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
視覚的にわかりやすくするため、UIのスクリーンショットなどを貼ると良いと思います。

2024-04-12 00:31 UTC, mitsuharu commented on book/manuscripts/iseki.md
> +今回は、TextField についての記事はいくつかありましたが、「数字のみ」かつ「小数点は 2 文字目以降の入力ができる」という実装の記事が見つからなかったので、実装してみました。
> 「数字のみ」かつ「小数点は 2 文字目以降の入力ができる」という実装の記事が見つからなかった

この導入で、なぜこの２つの実装が今までなかったか、背景やTextFieldの仕様？などを書いてあげると、読み手の読書欲を刺激すると思いました。書き手は執筆内容の背景を熟知してるので、背景を省略してもわかりますが、読者は初見なので背景は簡単でも書いてあげると親切だと思います

2024-04-12 00:31 UTC, mitsuharu commented on book/manuscripts/iseki.md
> +では実装した内容をご紹介します。
正規表現で入力可能な文字を制限していると思いますが、「実装した内容をご紹介します。」→コード だけだと、初心者は理解が難しいかもしれません。正規表現で入力制限している、そのために `FilteringTextInputFormatter.allow` で実現しているなど、実装コードの簡単な説明があると読み手がわかりやすくなると思いますー

2024-04-15 11:17 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +今回は、TextField についての記事はいくつかありましたが、「数字のみ」かつ「小数点は 2 文字目以降の入力ができる」という実装の記事が見つからなかったので、実装してみました。
こちらで修正してみました
[ca58686](https://github.com/yumemi-inc/daigirin-tbf16/pull/4/commits/ca58686142dab54b54dcdc65093cbbd162d69265)

2024-04-15 11:18 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +<hr class="page-break"/>
こちらで修正してみました。
[56c422e](https://github.com/yumemi-inc/daigirin-tbf16/pull/4/commits/56c422e8e517e445223c3bc3a340628e51ad7390)

2024-04-15 11:24 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +<hr class="page-break"/>
また、PDFで確認してみたところ感じだと改ページを入れた方がいいかなと考えているのですがどうでしょうか・・？
理由としては、`## 小数点の入力の制限をする`は次のページに新しく挿入したいと考えています

[ebook.pdf](https://github.com/yumemi-inc/daigirin-tbf16/files/14978175/ebook.pdf)

2024-04-15 11:25 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +数字のみの制限をするのはとても簡単に作ることができます。たった 2 行で実装することができます。
こちらで修正しました。
[d601366](https://github.com/yumemi-inc/daigirin-tbf16/pull/4/commits/d601366d4e57a706fb5c75c78c8b441fe9887ac4)

2024-04-15 12:52 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +では実装した内容をご紹介します。
こちらで記載してみました。
[ee3e7e6](https://github.com/yumemi-inc/daigirin-tbf16/pull/4/commits/ee3e7e69bfc8ffcec21e2e5f0feb02335962763f)

2024-04-15 12:52 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +今回は、TextField についての記事はいくつかありましたが、「数字のみ」かつ「小数点は 2 文字目以降の入力ができる」という実装の記事が見つからなかったので、実装してみました。
こちらで記載してみました。
[ee3e7e6](https://github.com/yumemi-inc/daigirin-tbf16/pull/4/commits/ee3e7e69bfc8ffcec21e2e5f0feb02335962763f)

2024-04-16 00:36 UTC, mitsuharu approved these changes
OK

2024-04-16 00:36 UTC, mitsuharu commented on book/vivliostyle.config.js
> +    'iseki.md',
この記事が `各章の原稿` ではなく `著者紹介` の方に追加されてます。
（記事順番は後で調整するのでこのままでもよいです）

2024-04-16 01:34 UTC, iseruuuuu commented on book/vivliostyle.config.js
> +    'iseki.md',
調整をお願いできたらなと思っております🙇

2024-04-16 05:36 UTC, usami-k commented on book/manuscripts/iseki.md
> +<hr class="page-break"/>
> 改ページを入れた方がいいかなと考えているのですがどうでしょうか・・？

一般論として、ページ下部に大きな余白があるのは書籍として見映えが良くない感はあります。

ただ、個人的な感覚やこだわりを優先していただいて問題ありません！

2024-04-16 06:00 UTC, usami-k approved these changes

2024-04-17 01:30 UTC, iseruuuuu commented on book/manuscripts/iseki.md
> +<hr class="page-break"/>
承知いたしました！個人的にはこのままで行きたいのですが、ページの調整や全体の調整の際に、修正が必要そうであれば、この部分を修正していただいても構いません🙇

2024-04-17 01:31 UTC, iseruuuuu commented
LGTMいただきありがとうございます！！マージさせていただきます！！

2024-04-17 01:31 UTC, merged