feat: 「読むと LT がしたくてたまらなくなるマニュアル」を追加
yumemi-inc/daigirin-tbf16 pull request #7
Opened 2024-04-13 09:19 UTC by OHMORIYUSUKE

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +<img width=100% src="./omori/output_benpi.png">
この画像は利用は大丈夫なものですか？
この画像が唐突に表示されて、文中で触れていないのて、引用として適切か難しいと思いました。
引用サイトのロゴとして表示したいのか、その文字を引用したいのか曖昧に見えました。

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +### 「アウトプットしないのは知的な便秘」
`###` の機能は見出しなので、強調として使うなら、他のhtmlタグやcssを活用すると良さそう。

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +## はじめに
`## はじめに` となってますが、この節ですでに本文が始まっているように見えます。
（「はじめに」は一般的に導入部分を指すと思いますが、本文に入ってるように見えます）
節と項を並べて、構成が適切か、見出しの組み合わせを調整すると見やすくなると思います

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +<ins>[speakerdeck.com/konifar/30dian-deda-xi-nili-tu](https://speakerdeck.com/konifar/30dian-deda-xi-nili-tu)</ins>
このspeackerdeckのリンクが「30 点で打席に立つ」に掛かっているのは、
リンク先をタップして遷移するまで分からなかったです。

Qiitaやnotionのようにリンク先を自動で展開しないので、関連性を明確に提示する必要があります。
リンクを注釈として入れて、何に掛かっているのかわかるようにするとよいです。
https://qiita.com/kamorits/items/6f342da395ad57468ae3#%E6%B3%A8%E9%87%88

また、このスライドの簡単な説明を入れて、適切に引用するとよいです。例えば↓

```
konifarさんが“めもりーさんと語るFindy Engineer Lab オフ会＠東京 LT [^konifar-connpass] ” で発表された「30 点で打席に立つ」は...

[^konifar-connpass]: https://findy.connpass.com/event/294069/
```

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +<ins>[speakerdeck.com/tomzoh/how-to-hack-the-cfp](https://speakerdeck.com/tomzoh/how-to-hack-the-cfp)</ins>
このスライドも適切に引用＆注釈をお願いします。

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +iOSDC 2023 セッション資料まとめ | <ins>[qiita.com/yuukiw00w/items/4a8c67a21618fd4626fc](https://qiita.com/yuukiw00w/items/4a8c67a21618fd4626fc)</ins>
リンクを並べているので、箇条書きだと見やすいと思います。

```
- PHPerKaigi2019 スライドまとめ
- iOSDC 2023 セッション資料まとめ
```

リンクも注釈で書くとスッキリすると思います。あとここはリンク紹介なので、PDFも考えて、リンクと注釈の併用が良いかもです。
```
- [PHPerKaigi2019 スライドまとめ](https://...) [^phpkaigi-slide-matome]

[^phpkaigi-slide-matome]: https://...
```

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +<ins>[www.microsoft.com/ja-jp/microsoft-365/powerpoint](https://www.microsoft.com/ja-jp/microsoft-365/powerpoint)</ins>
このあたりも突然urlが出てくるので、注釈表示がおすすめです。

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +「行動規範」(code of conduct)に違反するような発表を行うことは許されません。参加者の行動規範に違反するような言動も許されません。「ハラスメント」「性的な発言」「容姿に関する発言」など参加者を不快にさせる言動はしないようにしましょう。スライド内でも扱ってはいけません。以下の行動規範は YUMEMI.grow の行動規範です。LT をしに参加した勉強会や LT 会でも明記されていると
YUMEMI.growの簡単な説明があっても良いかも。ゆめみを知らない人が読んだら、YUMEMI.growとは？になるので、「ゆめみ有志が運営する勉強会」程度あるとわかりやすいです。

2024-04-15 05:58 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +## SHIROBAKO の杉江さんの言葉
セリフの一部、引用元があるから、問題ないはず（？）（求有識者）。

唐突にセリフができてくるので、「最後に、LTをこれからする人に、私が好きなアニメの１つSHIROBAKOからセリフを引用します。...」な説明はあってもよいと思いました。

2024-04-15 05:59 UTC, mitsuharu commented
リンク周りだけは、読んでて関連性がわかりにくかったので、修正をお願いします

2024-04-15 07:29 UTC, usami-k reviewed
興味深い内容で良いと思います！

![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)（対応必須ではありません）
文章での表現について、textlint を実行することをオススメします。慣れないうちは対応するのが大変だとは思いますが、なるべく指摘に従っておくほうが読みやすい文章になります。とくに、冗長な表現やひらがなで書く表現などは対応しておくと良いでしょう。

なお、textlint のルールの一部を無効化するのはありだと思います。たとえば、「！」や「？」を文章中に使いたいなら、次の指定を入れます。

```
<!-- textlint-disable ja-technical-writing/no-exclamation-question-mark -->
```

また、「かもしれません」「思います」などの表現を使いたければ、次の指定を入れます。

```
<!-- textlint-disable ja-technical-writing/ja-no-weak-phrase -->
```

このふたつは、一般的な技術文書では避けるべき表現ですが、今回はルールを無効にしたほうが活き活きと書けるだろうと感じます。

2024-04-15 07:49 UTC, usami-k commented on book/manuscripts/omoriLt.md
> +## SHIROBAKO の杉江さんの言葉
> セリフの一部、引用元があるから、問題ないはず（？）

引用であることが明確であり、出典が明記されていることから、著作権のルール的には大丈夫でしょう。

2024-04-15 09:40 UTC, OHMORIYUSUKE commented
[ebook.pdf](https://github.com/yumemi-inc/daigirin-tbf16/files/14976962/ebook.pdf)

レビューありがとうござういます。注釈でURLを示すように修正し、不要な画像は削除しました。

2024-04-15 16:37 UTC, OHMORIYUSUKE commented
申し訳ないのですが、私には commit 権限がないので大きな問題がなければマージしていただけると嬉しいです。

2024-04-16 00:44 UTC, mitsuharu requested changes

2024-04-16 00:44 UTC, mitsuharu commented on book/manuscripts/omoriLt.md
> +## class: content
[must]
これは大技林フォーマットの呪文なので、修正お願いします！
```suggestion
---
class: content
---
```

2024-04-16 04:59 UTC, usami-k commented on book/manuscripts/omoriLt.md
> +<!-- textlint-disable ja-technical-writing/ja-no-weak-phrase -->
textlint 関連のコメントを入れていただいているのですが、他の箇所で textlint に対応している様子がなさそうです。どうでしょうか？

textlint に対応しないなら、このコメントはむしろ入れないのがベターかと思います（このコメントがあることで、textlint に対応しているのかなと期待してしまうので）。

2024-04-16 16:29 UTC, OHMORIYUSUKE commented
[ebook.pdf](https://github.com/yumemi-inc/daigirin-tbf16/files/14999847/ebook.pdf)

こちらマークダウンを修正しPDFを生成し直しました。

2024-04-16 16:33 UTC, OHMORIYUSUKE commented on book/manuscripts/omoriLt.md
> +<!-- textlint-disable ja-technical-writing/ja-no-weak-phrase -->
ありがとうございます。私の文章では textlint のルールを無視しているので誤解を与えるタグを削除しました。

2024-04-17 00:56 UTC, mitsuharu approved these changes

2024-04-17 03:01 UTC, usami-k approved these changes

2024-04-17 04:13 UTC, merged